### ISSUE TITLE
Deployment: Repeated CF CLI steps to set environment variables

### ISSUE THREAD

**Issue by mandrici** [DFE-Digital/academy-transfers-api#9]
https://github.com/DFE-Digital/academy-transfers-api/blob/main/.github/workflows/deploy.yml

Problem: Using the citizen-of-planet-earth/cf-cli-action GitHub Action to deploy the code, it doesn't look like there's an option to run multiple commands. As a result, the Workflow file above becomes polluted by repeating the CF CLI step for each environment variable to be set. This issue is likely to grow as more environment variables are required. 

Desired Outcome: Ideally, we'd like to keep the workflow as slim and maintainable as possible.

**Comment by danielburnley** [comment]
Fixed in #25 - Now manually installs the CF API and uses manifest variables for setting environment variables 🎉
